import {
  FaEye,
  FaDownload,
  FaTrash,
  FaFilePdf,
  FaFileExcel,
} from "react-icons/fa";

function ReportFileRow({
  type,
  fileName,
  generatedBy,
  date,
  size,
}) {

  const isPdf = type === "pdf";

  return (
    <div className="bg-white rounded-3xl shadow p-6 flex items-center justify-between hover:shadow-xl transition-all">

      {/* Left */}
      <div className="flex items-center gap-6">

        {/* File Icon */}
        <div
          className={`
            w-16 h-16 rounded-2xl flex items-center justify-center text-2xl
            ${isPdf ? "bg-red-100 text-red-500" : "bg-blue-100 text-blue-500"}
          `}
        >

          {isPdf ? <FaFilePdf /> : <FaFileExcel />}

        </div>

        {/* Info */}
        <div>

          <h3 className="text-xl font-bold mb-1">
            {fileName}
          </h3>

          <p className="text-gray-500">
            Generated by {generatedBy} • {date} • {size}
          </p>

        </div>

      </div>

      {/* Actions */}
      <div className="flex items-center gap-6 text-gray-500 text-xl">

        <button className="hover:text-blue-600 transition-all">
          <FaEye />
        </button>

        <button className="hover:text-green-600 transition-all">
          <FaDownload />
        </button>

        <button className="hover:text-red-600 transition-all">
          <FaTrash />
        </button>

      </div>

    </div>
  );
}

export default ReportFileRow;